import React from 'react';
import { jsPDF } from 'jspdf';

/**
 * Fixed bottom summary bar shown after breach check + estimator are both complete.
 * Also generates a downloadable PDF report via jsPDF.
 */
export default function SummaryBanner({
  breachCount,
  optedOutCount,
  estimatedValue,
  breachList,
  email,
  isMockMode
}) {
  const handleDownloadPDF = () => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentW = pageW - margin * 2;
    let y = margin;

    // Helper to add text and track Y position
    const addLine = (text, size = 11, style = 'normal', color = [17, 24, 39]) => {
      doc.setFontSize(size);
      doc.setFont('helvetica', style);
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(String(text), contentW);
      doc.text(lines, margin, y);
      y += lines.length * (size * 0.45) + 3;
    };

    const addSpacer = (h = 5) => { y += h; };
    const addHRule = (color = [229, 231, 235]) => {
      doc.setDrawColor(...color);
      doc.line(margin, y, pageW - margin, y);
      y += 5;
    };

    // Light background
    doc.setFillColor(247, 248, 250);
    doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), 'F');

    // Header block
    doc.setFillColor(255, 255, 255);
    doc.rect(0, 0, pageW, 45, 'F');

    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(220, 38, 38); // red-600
    doc.text('DataTrace', margin, 22);

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(107, 114, 128);
    doc.text('Personal Data Exposure Report', margin, 32);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, margin, 39);

    y = 55;

    // Mock mode warning
    if (isMockMode) {
      doc.setFillColor(254, 252, 232);
      doc.rect(margin, y - 3, contentW, 12, 'F');
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(133, 77, 14);
      doc.text('⚠  DEMO MODE — breach data shown is sample data, not results for a specific email.', margin + 2, y + 5);
      y += 16;
    }

    // Summary stats section
    addLine('SUMMARY', 13, 'bold', [220, 38, 38]);
    addHRule([220, 38, 38]);

    addLine(`Email checked: ${isMockMode ? 'Demo mode (no email checked)' : email}`, 11, 'normal', [17, 24, 39]);
    addSpacer(2);
    addLine(`Breaches found: ${breachCount}`, 11, 'bold', breachCount > 0 ? [220, 38, 38] : [22, 163, 74]);
    addLine(`Data brokers in industry: 40 (documented by EFF and FTC)`, 11, 'normal', [107, 114, 128]);
    addLine(`Brokers opted out of: ${optedOutCount} / 40`, 11, 'normal', [107, 114, 128]);
    addLine(`Estimated annual data value: $${estimatedValue.toFixed(2)} (see disclaimer below)`, 11, 'bold', [17, 24, 39]);

    addSpacer(8);

    // Breach list
    if (breachList.length > 0) {
      addLine('BREACH DETAILS', 13, 'bold', [220, 38, 38]);
      addHRule([220, 38, 38]);

      breachList.forEach((breach, i) => {
        const dataClasses = (breach.DataClasses || []).join(', ');
        const hasHighRisk = (breach.DataClasses || []).some(d =>
          ['Passwords', 'Financial data'].includes(d)
        );

        addLine(`${i + 1}. ${breach.Name}`, 11, 'bold', hasHighRisk ? [220, 38, 38] : [17, 24, 39]);
        addLine(`   Date: ${breach.BreachDate}`, 9, 'normal', [107, 114, 128]);
        addLine(`   Exposed: ${dataClasses || 'Unknown'}`, 9, 'normal', [107, 114, 128]);
        addSpacer(3);

        // Page break if needed
        if (y > 250) {
          doc.addPage();
          doc.setFillColor(247, 248, 250);
          doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), 'F');
          y = margin;
        }
      });
    } else {
      addLine('No breaches found for this email.', 11, 'normal', [22, 163, 74]);
      addSpacer(8);
    }

    // Disclaimer
    addSpacer(5);
    addLine('ESTIMATE DISCLAIMER', 11, 'bold', [17, 24, 39]);
    addHRule([229, 231, 235]);
    addLine(
      'The "estimated annual data value" figure is based on publicly available platform ARPU data from Meta Q4 2023, Alphabet Q4 2023, Snap Q4 2023, Microsoft FY2023 earnings reports, Bloomberg Intelligence (2023), and the Financial Times (2023). These are estimates only — actual values vary by individual.',
      9, 'normal', [107, 114, 128]
    );

    addSpacer(10);

    // Footer
    addHRule([229, 231, 235]);
    addLine(
      'Generated by DataTrace  |  Data sources: HaveIBeenPwned, Meta, Alphabet, ByteDance earnings reports, EFF, FTC, Vanderbilt University',
      8, 'normal', [156, 163, 175]
    );
    addLine('datatrace.demo  |  Not legal or financial advice. For educational purposes.', 8, 'normal', [156, 163, 175]);

    doc.save('datatrace-report.pdf');
  };

  return (
    <div className="fixed bottom-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-sm border-t border-gray-200 shadow-lg">
      <div className="max-w-4xl mx-auto px-4 py-3 flex flex-wrap items-center gap-4">
        {/* Stats */}
        <div className="flex flex-wrap items-center gap-4 flex-1">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 bg-red-500 rounded-full flex-shrink-0"></span>
            <span className="text-sm text-gray-600">
              <span className="text-gray-900 font-bold">{breachCount}</span> breach{breachCount !== 1 ? 'es' : ''}
              {isMockMode && <span className="text-yellow-600 text-xs ml-1">(demo)</span>}
            </span>
          </div>

          <div className="flex items-center gap-2">
            <span className="w-2 h-2 bg-orange-500 rounded-full flex-shrink-0"></span>
            <span className="text-sm text-gray-600">
              <span className="text-gray-900 font-bold">40</span> known data brokers
            </span>
          </div>

          <div className="flex items-center gap-2">
            <span className="w-2 h-2 bg-yellow-500 rounded-full flex-shrink-0"></span>
            <span className="text-sm text-gray-600">
              Est. data value:{' '}
              <span className="text-gray-900 font-bold">${estimatedValue.toFixed(2)}/yr</span>
              <span className="text-xs text-gray-400 ml-1">(est.)</span>
            </span>
          </div>
        </div>

        {/* Download button */}
        <button
          onClick={handleDownloadPDF}
          className="bg-red-600 hover:bg-red-700 text-white text-sm font-semibold px-5 py-2 rounded-lg transition-colors flex items-center gap-2 flex-shrink-0"
        >
          <svg className="w-4 h-4" viewBox="0 0 16 16" fill="currentColor">
            <path d="M8 12l-4-4h2.5V4h3v4H12L8 12z"/>
            <path d="M2 13h12v1.5H2z"/>
          </svg>
          Download My Report
        </button>
      </div>
    </div>
  );
}
